//! Computes the structural difference between two bins.
//!
//! [`BinDiff::between`] returns two results. The change list contains one [`Change`] for every
//! value, object and dependency that differs, including removals. The patch is the `PTCH` that
//! [`Bin::diff_with`] generates for the same two bins. A patch cannot express every change, so
//! applying it to the base bin does not always reproduce the edited bin.
//!
//! [`BinDiff::between_patches`] compares two `PTCH` files: their delete lists, their objects
//! and their records. It generates no patch.

use std::collections::{HashMap, HashSet};

use indexmap::IndexMap;
use ltk_hash::BinHash;
use ltk_meta::{
    Bin, BinObject, BinOverride, DiffOptions, DiffReport, Lift, PropertyPatch, PropertyValueEnum,
    path::{MapKey, ValuePath},
    property::values,
};
use ltk_mimir_cache::Table;
use serde::Serialize;

use crate::{
    document::{TextLayout, to_text},
    hashes::{BinHashes, format_hash},
};

/// The kind of a [`Change`].
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum ChangeKind {
    /// The object exists only in the edited bin.
    ObjectAdded,
    /// The object exists only in the base bin.
    ObjectRemoved,
    /// The object exists in both bins with different classes.
    ObjectReplaced,
    /// A property, list item or map entry exists only in the edited bin.
    Added,
    /// A property, list item or map entry exists only in the base bin.
    Removed,
    /// The value exists in both bins and differs.
    Changed,
    /// The dependency exists only in the edited bin.
    DependencyAdded,
    /// The dependency exists only in the base bin.
    DependencyRemoved,
    /// The object is only in the delete list of the edited `PTCH` file.
    DeletionAdded,
    /// The object is only in the delete list of the base `PTCH` file.
    DeletionRemoved,
    /// Only the edited `PTCH` file has a record for this object and this property path.
    RecordAdded,
    /// Only the base `PTCH` file has a record for this object and this property path.
    RecordRemoved,
    /// Both `PTCH` files have the record, with different values.
    RecordChanged,
}

impl ChangeKind {
    /// Returns `true` for a change of a record of a `PTCH` file.
    pub fn is_record(self) -> bool {
        matches!(
            self,
            Self::RecordAdded | Self::RecordRemoved | Self::RecordChanged
        )
    }
}

/// One difference between two bins.
///
/// Hashes are formatted as in ritobin text: the name if a hashtable has one, otherwise `0x` hex.
/// Values are formatted as ritobin text.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct Change {
    pub kind: ChangeKind,
    /// The path hash of the object that contains the change. `None` for a dependency change.
    pub object: Option<String>,
    /// The path of the object, if the entry table has it.
    pub object_name: Option<String>,
    /// The class of the object. `None` for a change of a record or of a delete list, because
    /// a `PTCH` file does not store the class of the object that these address.
    pub class: Option<String>,
    /// The path of the value inside the object, or the property path of a record. `None` for
    /// a whole-object change, a dependency change or a delete list change.
    pub path: Option<String>,
    /// The ritobin type of the value.
    #[serde(rename = "type")]
    pub value_type: Option<String>,
    /// The value in the base bin.
    pub old: Option<String>,
    /// The value in the edited bin.
    pub new: Option<String>,
}

/// A location where the patch records a larger value than the changed one, because a patch
/// record cannot address the changed value directly.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct Lifted {
    pub object: String,
    pub object_name: Option<String>,
    pub path: String,
    pub reason: String,
}

/// The number of changes of each kind in a diff.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Serialize)]
pub struct Summary {
    pub objects_added: usize,
    pub objects_removed: usize,
    pub objects_replaced: usize,
    pub objects_changed: usize,
    pub values_added: usize,
    pub values_removed: usize,
    pub values_changed: usize,
    pub dependencies_added: usize,
    pub dependencies_removed: usize,
    pub deletions_added: usize,
    pub deletions_removed: usize,
    pub records_added: usize,
    pub records_removed: usize,
    pub records_changed: usize,
}

/// The difference between a base bin and an edited bin.
#[derive(Debug, Clone)]
pub struct BinDiff {
    /// All changes, grouped by object in the order of the edited bin. Objects that exist only
    /// in the base bin come last.
    pub changes: Vec<Change>,
    /// The `PTCH` generated by [`Bin::diff_with`].
    pub patch: BinOverride,
    /// The report of the patch: its record counts and its lifted locations.
    pub report: DiffReport,
    /// `true` if applying the patch to the base bin produces exactly the objects of the
    /// edited bin.
    ///
    /// It is `false` if the edited bin removes a property or a map entry, or removes an object
    /// while deletions are disabled. A patch has no record type for these changes.
    pub patch_is_exact: bool,
    /// `true` if `patch` was generated from two `PROP` bins. `false` for the difference of two
    /// `PTCH` files, which generates no patch. `patch` and `report` are then empty.
    pub has_patch: bool,
}

impl BinDiff {
    /// Computes the difference from `base` to `edited`. If `deletions` is `true`, the objects
    /// that exist only in `base` are added to the delete list of the patch.
    pub fn between(base: &Bin, edited: &Bin, hashes: &BinHashes, deletions: bool) -> Self {
        let mut walker = Walker {
            hashes,
            changes: Vec::new(),
            object: BinHash(0),
            class: BinHash(0),
            path: ValuePath::new(),
        };
        walker.bins(base, edited);

        let mut options = DiffOptions::default();
        options.deletions = deletions;
        let (patch, report) = base.diff_with(edited, hashes, &options);

        let mut patched = base.clone();
        patch.clone().apply(&mut patched);
        let patch_is_exact = patched.objects.len() == edited.objects.len()
            && edited.objects.iter().all(|(object_hash, object)| {
                patched
                    .objects
                    .get(object_hash)
                    .is_some_and(|patched| patched == object || same_text(patched, object))
            });

        Self {
            changes: walker.changes,
            patch,
            report,
            patch_is_exact,
            has_patch: true,
        }
    }

    /// Computes the difference from the `PTCH` file `base` to the `PTCH` file `edited`: the
    /// changes of the delete list, of the objects and of the records, in this order.
    ///
    /// A record is identified by its object and its property path. If a file has several
    /// records with the same object and path, the last one is compared, because it is the one
    /// that remains after the file is applied.
    pub fn between_patches(base: &BinOverride, edited: &BinOverride, hashes: &BinHashes) -> Self {
        let mut walker = Walker {
            hashes,
            changes: Vec::new(),
            object: BinHash(0),
            class: BinHash(0),
            path: ValuePath::new(),
        };
        walker.deletions(&base.deleted, &edited.deleted);
        walker.objects(&base.objects, &edited.objects);
        walker.records(&base.patches, &edited.patches);

        Self {
            changes: walker.changes,
            patch: BinOverride::new(),
            report: DiffReport::default(),
            patch_is_exact: true,
            has_patch: false,
        }
    }

    /// Returns `true` if the two bins have the same objects and dependencies.
    pub fn is_empty(&self) -> bool {
        self.changes.is_empty()
    }

    /// Counts the changes by kind.
    pub fn summary(&self) -> Summary {
        let mut summary = Summary::default();
        let mut changed_objects: Vec<&str> = Vec::new();
        for change in &self.changes {
            let counter = match change.kind {
                ChangeKind::ObjectAdded => &mut summary.objects_added,
                ChangeKind::ObjectRemoved => &mut summary.objects_removed,
                ChangeKind::ObjectReplaced => &mut summary.objects_replaced,
                ChangeKind::Added => &mut summary.values_added,
                ChangeKind::Removed => &mut summary.values_removed,
                ChangeKind::Changed => &mut summary.values_changed,
                ChangeKind::DependencyAdded => &mut summary.dependencies_added,
                ChangeKind::DependencyRemoved => &mut summary.dependencies_removed,
                ChangeKind::DeletionAdded => &mut summary.deletions_added,
                ChangeKind::DeletionRemoved => &mut summary.deletions_removed,
                ChangeKind::RecordAdded => &mut summary.records_added,
                ChangeKind::RecordRemoved => &mut summary.records_removed,
                ChangeKind::RecordChanged => &mut summary.records_changed,
            };
            *counter += 1;
            if matches!(
                change.kind,
                ChangeKind::Added | ChangeKind::Removed | ChangeKind::Changed
            ) && let Some(object) = change.object.as_deref()
                && changed_objects.last() != Some(&object)
            {
                changed_objects.push(object);
            }
        }
        summary.objects_changed = changed_objects.len();
        summary
    }

    /// Returns the lifted locations of the patch, with hashes resolved through `hashes`.
    pub fn lifted(&self, hashes: &BinHashes) -> Vec<Lifted> {
        self.report
            .lifted
            .iter()
            .map(|lift| Lifted {
                object: format_hash(lift.object_hash()),
                object_name: hashes
                    .lookup(Table::BinEntries, lift.object_hash())
                    .map(Into::into),
                path: lift.at().to_named(hashes).text,
                reason: match lift {
                    Lift::MapInsert { keys, .. } => format!("{keys} map entries inserted"),
                    Lift::Nameless { cause, .. } => cause.to_string(),
                    Lift::Mismatch { .. } => "shapes differ".to_owned(),
                    other => other.to_string(),
                },
            })
            .collect()
    }
}

/// Compares two bins recursively and records a [`Change`] for every difference.
struct Walker<'a> {
    hashes: &'a BinHashes,
    changes: Vec<Change>,
    /// The path hash of the object being compared.
    object: BinHash,
    /// The class of the object being compared.
    class: BinHash,
    /// The path of the value being compared, inside the object.
    path: ValuePath,
}

impl Walker<'_> {
    /// Compares the dependencies and the objects of two bins.
    fn bins(&mut self, base: &Bin, edited: &Bin) {
        for dependency in &edited.dependencies {
            if !base.dependencies.contains(dependency) {
                self.dependency(ChangeKind::DependencyAdded, dependency);
            }
        }
        for dependency in &base.dependencies {
            if !edited.dependencies.contains(dependency) {
                self.dependency(ChangeKind::DependencyRemoved, dependency);
            }
        }
        self.objects(&base.objects, &edited.objects);
    }

    /// Compares the delete lists of two `PTCH` files.
    fn deletions(&mut self, base: &[BinHash], edited: &[BinHash]) {
        let mut change = |kind, object: BinHash| {
            self.changes.push(Change {
                kind,
                object: Some(format_hash(object)),
                object_name: self
                    .hashes
                    .lookup(Table::BinEntries, object)
                    .map(Into::into),
                class: None,
                path: None,
                value_type: None,
                old: None,
                new: None,
            });
        };
        for object in edited.iter().filter(|object| !base.contains(object)) {
            change(ChangeKind::DeletionAdded, *object);
        }
        for object in base.iter().filter(|object| !edited.contains(object)) {
            change(ChangeKind::DeletionRemoved, *object);
        }
    }

    /// Compares the records of two `PTCH` files. The changes are grouped by object, in the
    /// order of the edited file. Records that only the base file has come last.
    fn records(&mut self, base: &[PropertyPatch], edited: &[PropertyPatch]) {
        // The last record of each object and path.
        let last = |records: &'_ [PropertyPatch]| {
            let mut by_key: IndexMap<(BinHash, String), PropertyValueEnum> = IndexMap::new();
            for record in records {
                let key = (record.object_hash, record.path.as_str().to_owned());
                by_key.insert(key, record.value.clone());
            }
            by_key
        };
        let (base, edited) = (last(base), last(edited));

        let mut changes: Vec<(BinHash, Change)> = Vec::new();
        let mut change = |kind, key: &(BinHash, String), old, new| {
            let text = |value: Option<&PropertyValueEnum>| {
                value.map(|value| value_text(value, self.hashes))
            };
            let (old, new) = (text(old), text(new));
            let value_type = match (&old, &new) {
                (Some((old_type, _)), Some((new_type, _))) if old_type != new_type => {
                    Some(format!("{old_type} -> {new_type}"))
                }
                (_, Some((value_type, _))) | (Some((value_type, _)), None) => {
                    Some(value_type.clone())
                }
                (None, None) => None,
            };
            changes.push((
                key.0,
                Change {
                    kind,
                    object: Some(format_hash(key.0)),
                    object_name: self.hashes.lookup(Table::BinEntries, key.0).map(Into::into),
                    class: None,
                    path: Some(key.1.clone()),
                    value_type,
                    old: old.map(|(_, text)| text),
                    new: new.map(|(_, text)| text),
                },
            ));
        };
        for (key, value) in &edited {
            match base.get(key) {
                None => change(ChangeKind::RecordAdded, key, None, Some(value)),
                Some(existing) if existing != value => {
                    change(ChangeKind::RecordChanged, key, Some(existing), Some(value));
                }
                Some(_) => {}
            }
        }
        for (key, value) in &base {
            if !edited.contains_key(key) {
                change(ChangeKind::RecordRemoved, key, Some(value), None);
            }
        }

        // A stable sort by the first position of each object keeps the records of one object
        // together, so that the `summary` format prints one heading per object.
        let mut order: Vec<BinHash> = Vec::new();
        for (object, _) in &changes {
            if !order.contains(object) {
                order.push(*object);
            }
        }
        changes.sort_by_key(|(object, _)| order.iter().position(|first| first == object));
        self.changes
            .extend(changes.into_iter().map(|(_, change)| change));
    }

    /// Compares two object lists.
    fn objects(
        &mut self,
        base: &IndexMap<BinHash, BinObject>,
        edited: &IndexMap<BinHash, BinObject>,
    ) {
        for (object_hash, object) in edited {
            self.enter(object);
            match base.get(object_hash) {
                None => self.whole_object(ChangeKind::ObjectAdded, None, None),
                Some(existing) if existing.class_hash != object.class_hash => self.whole_object(
                    ChangeKind::ObjectReplaced,
                    Some(self.class_name(existing.class_hash)),
                    Some(self.class_name(object.class_hash)),
                ),
                Some(existing) => {
                    self.properties(&existing.properties, &object.properties, object.class_hash)
                }
            }
        }
        for (object_hash, object) in base {
            if !edited.contains_key(object_hash) {
                self.enter(object);
                self.whole_object(ChangeKind::ObjectRemoved, None, None);
            }
        }
    }

    /// Sets `object` as the current object and resets the path.
    fn enter(&mut self, object: &BinObject) {
        self.object = object.path_hash;
        self.class = object.class_hash;
        self.path = ValuePath::new();
    }

    /// Returns the name of `class`. Falls back to the hash as hex if the type table has no
    /// name for it.
    fn class_name(&self, class: BinHash) -> String {
        match self.hashes.lookup(Table::BinTypes, class) {
            Some(name) => name.into_owned(),
            None => format_hash(class),
        }
    }

    /// Records a dependency change.
    fn dependency(&mut self, kind: ChangeKind, dependency: &str) {
        let (old, new) = match kind {
            ChangeKind::DependencyRemoved => (Some(dependency.to_owned()), None),
            _ => (None, Some(dependency.to_owned())),
        };
        self.changes.push(Change {
            kind,
            object: None,
            object_name: None,
            class: None,
            path: None,
            value_type: None,
            old,
            new,
        });
    }

    /// Records a change of the whole current object.
    fn whole_object(&mut self, kind: ChangeKind, old: Option<String>, new: Option<String>) {
        let change = self.change(kind, None, None, old, new);
        self.changes.push(change);
    }

    /// Builds a [`Change`] for the current object.
    fn change(
        &self,
        kind: ChangeKind,
        path: Option<String>,
        value_type: Option<String>,
        old: Option<String>,
        new: Option<String>,
    ) -> Change {
        Change {
            kind,
            object: Some(format_hash(self.object)),
            object_name: self
                .hashes
                .lookup(Table::BinEntries, self.object)
                .map(Into::into),
            class: Some(self.class_name(self.class)),
            path,
            value_type,
            old,
            new,
        }
    }

    /// Records a change of the value at the current path.
    fn value_change(
        &mut self,
        kind: ChangeKind,
        old: Option<&PropertyValueEnum>,
        new: Option<&PropertyValueEnum>,
    ) {
        let old = old.map(|value| value_text(value, self.hashes));
        let new = new.map(|value| value_text(value, self.hashes));
        let value_type = match (&old, &new) {
            (Some((old_type, _)), Some((new_type, _))) if old_type != new_type => {
                Some(format!("{old_type} -> {new_type}"))
            }
            (_, Some((value_type, _))) | (Some((value_type, _)), None) => Some(value_type.clone()),
            (None, None) => None,
        };
        let path = self.path.to_named(self.hashes).text;
        let change = self.change(
            kind,
            Some(path),
            value_type,
            old.map(|(_, text)| text),
            new.map(|(_, text)| text),
        );
        self.changes.push(change);
    }

    /// Compares the properties of two objects or structs of class `class`.
    fn properties(
        &mut self,
        base: &IndexMap<BinHash, PropertyValueEnum>,
        edited: &IndexMap<BinHash, PropertyValueEnum>,
        class: BinHash,
    ) {
        for (field, value) in edited {
            self.path.push_field(*field, class);
            match base.get(field) {
                Some(existing) => self.value(existing, value),
                None => self.value_change(ChangeKind::Added, None, Some(value)),
            }
            self.path.pop();
        }
        for (field, value) in base {
            if !edited.contains_key(field) {
                self.path.push_field(*field, class);
                self.value_change(ChangeKind::Removed, Some(value), None);
                self.path.pop();
            }
        }
    }

    /// Compares two values. Recurses into structs, lists, options and maps that have the same
    /// class or item kinds. Records any other difference as one `Changed`.
    fn value(&mut self, base: &PropertyValueEnum, edited: &PropertyValueEnum) {
        use PropertyValueEnum as V;

        if base == edited {
            return;
        }
        match (base, edited) {
            (V::Struct(b), V::Struct(e))
            | (V::Embedded(values::Embedded(b)), V::Embedded(values::Embedded(e)))
                if b.class_hash == e.class_hash =>
            {
                self.properties(&b.properties, &e.properties, e.class_hash);
            }
            (V::Container(b), V::Container(e))
            | (
                V::UnorderedContainer(values::UnorderedContainer(b)),
                V::UnorderedContainer(values::UnorderedContainer(e)),
            ) if b.item_kind() == e.item_kind() => self.items(b.items(), e.items()),
            (V::Optional(b), V::Optional(e)) if b.item_kind() == e.item_kind() => {
                match (b.value(), e.value()) {
                    (Some(b), Some(e)) => {
                        self.path.push_index(0);
                        self.value(b, e);
                        self.path.pop();
                    }
                    _ => self.changed(base, edited),
                }
            }
            (V::Map(b), V::Map(e))
                if b.key_kind() == e.key_kind() && b.value_kind() == e.value_kind() =>
            {
                if !self.entries(b, e) {
                    self.changed(base, edited);
                }
            }
            _ => self.changed(base, edited),
        }
    }

    /// Records two unequal values as `Changed`, unless their debug text is equal. Two values
    /// that contain the same NaN compare unequal, and that is not a change.
    fn changed(&mut self, base: &PropertyValueEnum, edited: &PropertyValueEnum) {
        if !same_text(base, edited) {
            self.value_change(ChangeKind::Changed, Some(base), Some(edited));
        }
    }

    /// Compares two lists by index. An item beyond the end of the shorter list is recorded as
    /// `Added` or `Removed`.
    fn items(&mut self, base: &[PropertyValueEnum], edited: &[PropertyValueEnum]) {
        for index in 0..base.len().max(edited.len()) {
            self.path.push_index(index);
            match (base.get(index), edited.get(index)) {
                (Some(b), Some(e)) => self.value(b, e),
                (None, Some(e)) => self.value_change(ChangeKind::Added, None, Some(e)),
                (Some(b), None) => self.value_change(ChangeKind::Removed, Some(b), None),
                (None, None) => {}
            }
            self.path.pop();
        }
    }

    /// Compares two maps by key. Returns `false` without recording a change if a key cannot be
    /// converted to a [`MapKey`] or if a map has a duplicate key. The caller then records the
    /// whole map as `Changed`.
    fn entries(&mut self, base: &values::Map, edited: &values::Map) -> bool {
        let keys = |map: &values::Map| {
            map.entries()
                .iter()
                .map(|(key, _)| MapKey::try_from(key).ok())
                .collect::<Option<Vec<_>>>()
        };
        let (Some(base_keys), Some(edited_keys)) = (keys(base), keys(edited)) else {
            return false;
        };
        let base_index: HashMap<&MapKey, &PropertyValueEnum> = base_keys
            .iter()
            .zip(base.entries())
            .map(|(key, (_, value))| (key, value))
            .collect();
        let edited_index: HashSet<&MapKey> = edited_keys.iter().collect();
        if base_index.len() != base_keys.len() || edited_index.len() != edited_keys.len() {
            return false;
        }

        for (key, (_, value)) in edited_keys.iter().zip(edited.entries()) {
            self.path.push_key(key.clone());
            match base_index.get(key) {
                Some(existing) => self.value(existing, value),
                None => self.value_change(ChangeKind::Added, None, Some(value)),
            }
            self.path.pop();
        }
        for (key, (_, value)) in base_keys.iter().zip(base.entries()) {
            if !edited_index.contains(key) {
                self.path.push_key(key.clone());
                self.value_change(ChangeKind::Removed, Some(value), None);
                self.path.pop();
            }
        }
        true
    }
}

/// Returns `true` if the debug text of `a` and `b` is equal. This detects values that compare
/// unequal only because they contain a NaN, which is not equal to itself.
fn same_text<T: std::fmt::Debug>(a: &T, b: &T) -> bool {
    format!("{a:?}") == format!("{b:?}")
}

/// Returns the ritobin type and the ritobin text of `value`, formatted as the printer formats a
/// property of an object.
pub fn value_text(value: &PropertyValueEnum, hashes: &BinHashes) -> (String, String) {
    // The printer has no function that prints a single value. The value is printed as the only
    // property of a bin with one object, and `cut_value` extracts it from the output.
    let bin = Bin::builder()
        .object(
            BinObject::builder(1u32, 1u32)
                .property(1u32, value.clone())
                .build(),
        )
        .build();
    let layout = TextLayout {
        inline_structs: false,
        ..TextLayout::default()
    };
    to_text(&bin.into(), layout, hashes)
        .ok()
        .and_then(|text| cut_value(&text, layout.indent_size))
        .unwrap_or_else(|| (String::new(), format!("{value:?}")))
}

/// Extracts the type and the value of the only property from the printed text of a bin with one
/// object. Removes the indentation of the object from the value.
fn cut_value(text: &str, indent_size: usize) -> Option<(String, String)> {
    let property_indent = " ".repeat(indent_size * 2);
    let object_close = format!("{}}}", " ".repeat(indent_size));

    let mut lines = text
        .lines()
        .skip_while(|line| !line.starts_with(&property_indent));
    let first = lines.next()?.strip_prefix(&property_indent)?;
    let (_, typed) = first.split_once(": ")?;
    let (value_type, head) = typed.split_once(" = ")?;

    let mut value = head.to_owned();
    for line in lines.take_while(|line| *line != object_close) {
        value.push('\n');
        value.push_str(line.strip_prefix(&property_indent).unwrap_or(line));
    }
    Some((value_type.to_owned(), value))
}

#[cfg(test)]
mod tests {
    use ltk_hash::Hash as _;
    use ltk_meta::property::Kind;

    use super::*;

    const OBJECT: u32 = 0x1111_0001;
    const CLASS: u32 = 0xaaaa_0001;

    fn bin(properties: impl IntoIterator<Item = (u32, PropertyValueEnum)>) -> Bin {
        let mut object = BinObject::new(OBJECT, CLASS);
        for (field, value) in properties {
            object.properties.insert(BinHash(field), value);
        }
        Bin::builder().object(object).build()
    }

    fn diff(base: &Bin, edited: &Bin) -> BinDiff {
        BinDiff::between(base, edited, &BinHashes::none(), false)
    }

    fn kinds(diff: &BinDiff) -> Vec<ChangeKind> {
        diff.changes.iter().map(|change| change.kind).collect()
    }

    #[test]
    fn between_patches_compares_delete_lists_objects_and_records() {
        use ltk_meta::path::PropertyPath;

        let path = |text: &str| PropertyPath::new(text).unwrap();
        let object = |value: i32| {
            let mut object = BinObject::new(0x3u32, CLASS);
            object
                .properties
                .insert(BinHash(0x10), values::I32::new(value).into());
            object
        };
        let base = BinOverride::builder()
            .delete(0x1u32)
            .delete(0x2u32)
            .object(object(1))
            .set(OBJECT, path("Size"), values::I32::new(1))
            .set(OBJECT, path("Name"), values::String::from("base"))
            .set(OBJECT, path("Removed"), values::Bool::new(true))
            .build();
        // The record of `Size` is written twice. The last one is compared.
        let edited = BinOverride::builder()
            .delete(0x2u32)
            .delete(0x9u32)
            .object(object(2))
            .set(OBJECT, path("Size"), values::I32::new(7))
            .set(OBJECT, path("Name"), values::String::from("base"))
            .set(0x5u32, path("Added"), values::F32::new(0.5))
            .set(OBJECT, path("Size"), values::I32::new(2))
            .build();

        let diff = BinDiff::between_patches(&base, &edited, &BinHashes::none());
        assert!(!diff.has_patch);
        assert!(diff.patch.is_empty());
        let rows: Vec<_> = diff
            .changes
            .iter()
            .map(|change| {
                (
                    change.kind,
                    change.object.as_deref().unwrap(),
                    change.path.as_deref(),
                    change.old.as_deref(),
                    change.new.as_deref(),
                )
            })
            .collect();
        assert_eq!(
            rows,
            [
                (ChangeKind::DeletionAdded, "0x00000009", None, None, None),
                (ChangeKind::DeletionRemoved, "0x00000001", None, None, None),
                (
                    ChangeKind::Changed,
                    "0x00000003",
                    Some("00000010"),
                    Some("1"),
                    Some("2")
                ),
                (
                    ChangeKind::RecordChanged,
                    "0x11110001",
                    Some("Size"),
                    Some("1"),
                    Some("2")
                ),
                (
                    ChangeKind::RecordRemoved,
                    "0x11110001",
                    Some("Removed"),
                    Some("true"),
                    None
                ),
                (
                    ChangeKind::RecordAdded,
                    "0x00000005",
                    Some("Added"),
                    None,
                    Some("0.5")
                ),
            ]
        );
        // A record change has no class, because a record stores none.
        assert!(
            diff.changes
                .iter()
                .all(|change| change.class.is_none() == (change.kind != ChangeKind::Changed))
        );

        let summary = diff.summary();
        assert_eq!((summary.deletions_added, summary.deletions_removed), (1, 1));
        assert_eq!(
            (
                summary.records_added,
                summary.records_removed,
                summary.records_changed
            ),
            (1, 1, 1)
        );
        assert_eq!(summary.values_changed, 1);

        let same = BinDiff::between_patches(&base, &base, &BinHashes::none());
        assert!(same.is_empty());
    }

    #[test]
    fn value_text_returns_type_and_value() {
        let hashes = BinHashes::none();
        assert_eq!(
            value_text(&values::I32::new(42).into(), &hashes),
            ("i32".to_owned(), "42".to_owned())
        );
        assert_eq!(
            value_text(&values::String::from("a = b: c").into(), &hashes),
            ("string".to_owned(), "\"a = b: c\"".to_owned())
        );

        let optional = values::Optional::new(Kind::U32, Some(values::U32::new(7).into())).unwrap();
        assert_eq!(
            value_text(&optional.into(), &hashes),
            ("option[u32]".to_owned(), "{ 7 }".to_owned())
        );
    }

    #[test]
    fn value_text_removes_indentation_of_multi_line_value() {
        let mut inner = values::Struct {
            class_hash: BinHash(0xc1),
            properties: IndexMap::new(),
        };
        inner
            .properties
            .insert(BinHash(0x10), values::I32::new(1).into());
        inner
            .properties
            .insert(BinHash(0x11), values::I32::new(2).into());

        let (value_type, text) = value_text(&values::Embedded(inner).into(), &BinHashes::none());
        assert_eq!(value_type, "embed");
        assert_eq!(text, "0xc1 {\n    0x10: i32 = 1\n    0x11: i32 = 2\n}");
    }

    #[test]
    fn identical_bins_produce_no_changes_and_empty_patch() {
        let base = bin([(0x10, values::I32::new(1).into())]);
        let diff = diff(&base, &base.clone());
        assert!(diff.is_empty());
        assert!(diff.patch.is_empty());
        assert!(diff.patch_is_exact);
    }

    #[test]
    fn changed_added_and_removed_properties_are_reported() {
        let base = bin([
            (0x10, values::I32::new(1).into()),
            (0x11, values::Bool::new(true).into()),
        ]);
        let edited = bin([
            (0x10, values::I32::new(2).into()),
            (0x12, values::String::from("new").into()),
        ]);

        let diff = diff(&base, &edited);
        assert_eq!(
            kinds(&diff),
            [ChangeKind::Changed, ChangeKind::Added, ChangeKind::Removed]
        );

        let changed = &diff.changes[0];
        assert_eq!(changed.object.as_deref(), Some("0x11110001"));
        assert_eq!(changed.class.as_deref(), Some("0xaaaa0001"));
        assert_eq!(changed.path.as_deref(), Some("00000010"));
        assert_eq!(changed.value_type.as_deref(), Some("i32"));
        assert_eq!(
            (changed.old.as_deref(), changed.new.as_deref()),
            (Some("1"), Some("2"))
        );

        let summary = diff.summary();
        assert_eq!(summary.objects_changed, 1);
        assert_eq!(
            (
                summary.values_changed,
                summary.values_added,
                summary.values_removed
            ),
            (1, 1, 1)
        );
    }

    #[test]
    fn removed_property_makes_patch_inexact() {
        let base = bin([
            (0x10, values::I32::new(1).into()),
            (0x11, values::Bool::new(true).into()),
        ]);
        let edited = bin([(0x10, values::I32::new(1).into())]);

        let diff = diff(&base, &edited);
        assert_eq!(kinds(&diff), [ChangeKind::Removed]);
        assert!(!diff.patch_is_exact);
    }

    #[test]
    fn list_items_are_compared_by_index() {
        let list = |items: &[u32]| -> PropertyValueEnum {
            values::Container::new(
                Kind::U32,
                items
                    .iter()
                    .map(|item| values::U32::new(*item).into())
                    .collect(),
            )
            .unwrap()
            .into()
        };
        let diff = diff(
            &bin([(0x10, list(&[1, 2, 3]))]),
            &bin([(0x10, list(&[1, 9]))]),
        );

        assert_eq!(kinds(&diff), [ChangeKind::Changed, ChangeKind::Removed]);
        assert_eq!(diff.changes[0].path.as_deref(), Some("00000010[1]"));
        assert_eq!(diff.changes[1].path.as_deref(), Some("00000010[2]"));
    }

    #[test]
    fn map_entries_are_compared_by_key() {
        let map = |entries: &[(u32, i32)]| -> PropertyValueEnum {
            values::Map::new(
                Kind::Hash,
                Kind::I32,
                entries
                    .iter()
                    .map(|(key, value)| {
                        (
                            values::Hash::new(*key).into(),
                            values::I32::new(*value).into(),
                        )
                    })
                    .collect(),
            )
            .unwrap()
            .into()
        };
        let diff = diff(
            &bin([(0x10, map(&[(1, 10), (2, 20)]))]),
            &bin([(0x10, map(&[(2, 21), (3, 30)]))]),
        );

        assert_eq!(
            kinds(&diff),
            [ChangeKind::Changed, ChangeKind::Added, ChangeKind::Removed]
        );
        assert_eq!(
            (
                diff.changes[0].old.as_deref(),
                diff.changes[0].new.as_deref()
            ),
            (Some("20"), Some("21"))
        );
    }

    #[test]
    fn added_and_removed_objects_and_dependencies_are_reported() {
        let base = Bin::builder()
            .dependency("shared.bin")
            .dependency("old.bin")
            .object(BinObject::new(0x1, 0xc1))
            .object(BinObject::new(0x2, 0xc1))
            .build();
        let edited = Bin::builder()
            .dependency("shared.bin")
            .dependency("new.bin")
            .object(BinObject::new(0x2, 0xc2))
            .object(BinObject::new(0x3, 0xc1))
            .build();

        let diff = diff(&base, &edited);
        assert_eq!(
            kinds(&diff),
            [
                ChangeKind::DependencyAdded,
                ChangeKind::DependencyRemoved,
                ChangeKind::ObjectReplaced,
                ChangeKind::ObjectAdded,
                ChangeKind::ObjectRemoved,
            ]
        );
    }

    #[test]
    fn deletions_add_removed_objects_to_patch_delete_list() {
        let base = Bin::builder()
            .object(BinObject::new(0x1, 0xc1))
            .object(BinObject::new(0x2, 0xc1))
            .build();
        let edited = Bin::builder().object(BinObject::new(0x1, 0xc1)).build();

        let kept = BinDiff::between(&base, &edited, &BinHashes::none(), false);
        assert!(kept.patch.deleted.is_empty());
        assert!(!kept.patch_is_exact);

        let deleted = BinDiff::between(&base, &edited, &BinHashes::none(), true);
        assert_eq!(deleted.patch.deleted, [BinHash(0x2)]);
        assert!(deleted.patch_is_exact);
    }

    #[test]
    fn unnamed_field_change_is_lifted_to_whole_object() {
        let field = BinHash::hash_str("mNotInAnyTable").0;
        let base = bin([(field, values::I32::new(1).into())]);
        let edited = bin([(field, values::I32::new(2).into())]);

        let diff = diff(&base, &edited);
        assert_eq!(kinds(&diff), [ChangeKind::Changed]);
        assert!(diff.patch.patches.is_empty());
        assert_eq!(diff.patch.objects.len(), 1);
        assert!(diff.patch_is_exact);

        let lifted = diff.lifted(&BinHashes::none());
        assert_eq!(lifted.len(), 1);
        assert_eq!(lifted[0].object, "0x11110001");
    }

    #[test]
    fn equal_nan_values_are_not_reported() {
        let nan = |other: i32| {
            let list = values::Container::new(
                Kind::F32,
                vec![
                    values::F32::new(1.0).into(),
                    values::F32::new(f32::NAN).into(),
                ],
            )
            .unwrap();
            bin([
                (0x10, values::F32::new(f32::NAN).into()),
                (0x11, list.into()),
                (0x12, values::I32::new(other).into()),
            ])
        };

        let same = diff(&nan(1), &nan(1));
        assert!(same.is_empty());
        assert!(same.patch_is_exact);

        let other = diff(&nan(1), &nan(2));
        assert_eq!(kinds(&other), [ChangeKind::Changed]);
        assert_eq!(other.changes[0].path.as_deref(), Some("00000012"));
    }

    #[test]
    fn map_with_duplicate_key_is_reported_as_one_change() {
        let map = |entries: &[(u32, i32)]| -> PropertyValueEnum {
            values::Map::new(
                Kind::U32,
                Kind::I32,
                entries
                    .iter()
                    .map(|(key, value)| {
                        (
                            values::U32::new(*key).into(),
                            values::I32::new(*value).into(),
                        )
                    })
                    .collect(),
            )
            .unwrap()
            .into()
        };
        let diff = diff(
            &bin([(0x10, map(&[(1, 1), (1, 2)]))]),
            &bin([(0x10, map(&[(1, 2)]))]),
        );

        assert_eq!(kinds(&diff), [ChangeKind::Changed]);
        assert_eq!(diff.changes[0].path.as_deref(), Some("00000010"));
        assert_eq!(diff.changes[0].value_type.as_deref(), Some("map[u32, i32]"));
    }

    #[test]
    fn type_change_reports_both_types() {
        let diff = diff(
            &bin([(0x10, values::I32::new(1).into())]),
            &bin([(0x10, values::U32::new(1).into())]),
        );
        assert_eq!(kinds(&diff), [ChangeKind::Changed]);
        assert_eq!(diff.changes[0].value_type.as_deref(), Some("i32 -> u32"));
    }
}
